# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/redis-cache
    username: postgres
    password: admin
  # JPA properties
  jpa:
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 8
  # Redis cache
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

# Port
server:
  port: 8080

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui
